# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea3609c6d3c3e0994779249560f3401d3ed7d4cbf34c245463df4d4a2bef1cc9e2a7d71a7740b74b58399cce55caa1a6c66f996f40a7b8e079578c62a482739e

test:
  secret_key_base: 2edf3fe933cd045afd0c5320983f1564a9a0c4e3ba2e5524322544d743a18abfb25968af73367847d428687aeed3e5ee3020ce138d1ac45755a62304e03e8f5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
